### ISSUE TITLE
Schema files with doobie-codegen turned off for all lines causes exceptions to be thrown

### ISSUE THREAD

**Issue by kennyboy** [mdmoss/doobie-codegen#40]
A comment on the first line seems to be needed to trigger this

Example file:
```
-- A comment
-- doobie-codegen: off
DROP TABLE tbl;
-- doobie-codegen: on
```

```
Unexpected end of input, expected AlterSequence, With, Update, Commit, CreateTable, Begin, CreateExtension, DropView, Delete, DropTable, CreateView, CreateSchema, Insert, CreateIndex or AlterTable (line 1, column 1):

^
[error] (run-main-4) ParseError(Position(0,1,1), Position(0,1,1), <21 traces>)
ParseError(Position(0,1,1), Position(0,1,1), <21 traces>)
        at org.parboiled2.Parser.done$1(Parser.scala:185)
        at org.parboiled2.Parser.phase4_collectRuleTraces$1(Parser.scala:196)
        at org.parboiled2.Parser.__run(Parser.scala:209)
        at mdmoss.doobiegen.Runner$$anonfun$run$1.apply(Runner.scala:76)
        at mdmoss.doobiegen.Runner$$anonfun$run$1.apply(Runner.scala:75)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at mdmoss.doobiegen.Runner$.run(Runner.scala:75)
```

**Comment by markseatang** [comment]
Extending this bug:
codegen will throw if the last thing it reads is a comment

e.g.
```

CREATE TABLE tbl;

-- This is the last thing doobie-codegen reads before it gets turned off and on again
-- doobie-codegen: off
DROP TABLE tbl;
-- doobie-codegen: on

```
or
```

CREATE TABLE tbl;

-- doobie-codegen: off
DROP TABLE tbl;
-- doobie-codegen: on
-- This is the last thing doobie-codegen reads before it gets turned off and on again

```
